services:
  - type: web
    name: drugbit-frontend
    env: node
    plan: startar
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://drug-6.onrender.com
      - key: NEXT_PUBLIC_SITEMAP_KEY
        value: your-sitemap-key
      - key: G-NGJDELB5GC
        value: https://data.drugbit.info
